suggestion_generation:
  description: >
    Generate actionable suggestions for resolving each classified support ticket.
    The suggestions should be based on:
    - Issue Type: Tailor suggestions to the specific type of issue reported.
    - Historical Data: Use historical data such as resolution_time_minutes and
      satisfaction_rating to inform the suggestions.
    - Customer Feedback: Incorporate insights from customer_comments to
      customize the suggestions further.

    The goal is to provide clear, actionable steps that the support team can
    take to resolve each issue efficiently and effectively.
  expected_output: >
    A list of actionable suggestions linked to each classified support ticket,
    optimized for quick and effective resolution by the support team.
  agent: suggestion_generation_agent
  

table_generation:
  description: >
    Generate tables that summarize the key metrics and trends observed in the
    support data, including:
    - Issue Classification Results: A table summarizing the frequency and
      priority levels of different issue types.
    - Agent Performance: A table showing the performance of different agents
      based on resolution times and customer satisfaction scores.
    - Customer Satisfaction: A table summarizing customer satisfaction ratings
      over time.

    These tables will serve as the foundation for generating charts in the next
    task.
  expected_output: >
    A set of tables summarizing the key metrics and trends observed in the
    support data, ready to be used for chart generation.
  agent: reporting_agent
  

chart_generation:
  description: >
    Generate charts based on the tables provided by the previous task. The
    charts should include:
    - Issue Distribution: A chart showing the distribution of different issue
      types.
    - Priority Levels: A chart depicting the breakdown of tickets by priority
      level.
    - Resolution Times: A trend line showing average resolution times over the
      past months.
    - Customer Satisfaction: A bar chart or trend line showing customer
      satisfaction ratings over time.
    - Agent Performance: A chart showing the performance of different agents
      based on resolution times and customer satisfaction scores.

    Save the charts as image files in the current directory.

    Ensure that the charts are saved as image files, and generate URLs for these
    images so they can be easily embedded into the final report.
  expected_output: >
    A set of charts that visually represent the key metrics and trends observed
    in the support data, ready to be integrated into the final report.
  agent: chart_generation_agent
  

final_report_assembly:
  description: >
    Assemble the final report by integrating the tables and charts generated in
    the previous tasks. The report should include:
    
    - Executive Summary: A brief overview of the key findings and recommendations.
    
    - Issue Classification Results: Overview of the types of issues reported,
      their frequency, and priority levels, presented in tables and charts.
    
    - Agent Performance: Insights into the performance of support agents, based
      on metrics like resolution time and customer satisfaction, presented in
      tables and charts.
    
    - Customer Satisfaction: A summary of the customer satisfaction ratings and
      their trends over time, presented in tables and charts.
    
    - Suggested Actions: A summary of the actionable suggestions generated for
      each category of issue.
    
    - Conclusion: A summary of the key takeaways and next steps.

    The report should be formatted as a professional Markdown document with proper headers,
    sections, and formatting. Use the following structure:
    
    - # for main title
    - ## for major sections
    - ### for subsections
    - Bullet points for lists
    - Tables using markdown table syntax
    - Code blocks for data when appropriate
    
    Integrate tables and relevant charts side by side with appropriate formatting.
    The report should be ready for distribution to stakeholders, providing valuable 
    insights in a clear, organized, and professional manner.
  expected_output: >
    A comprehensive final report that integrates tables, charts, and actionable
    insights into a properly formatted Markdown document with clear sections, 
    headers, and professional presentation.
    Don't add '```' or '```markdown' to the report.
  agent: reporting_agent
  context:
    - suggestion_generation
    - table_generation
    - chart_generation
  









